# Servicio Portainer
version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: PORTAINER-ADM
    hostname: "Portainer-ADM"
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9000:9000/tcp" # Puerto TCP Administracion Web.
    restart: unless-stopped
    network_mode: bridge
#---------------------------------------------------------------#
# Servicio Docker Controller Bot
  docker-controller-bot:
    environment:
      - CONTAINER_NAME=DOCKER-BOT
      - TELEGRAM_TOKEN=${BOT_TOKEN}
      - TELEGRAM_ADMIN=${CHAT_ID}
      - TZ=${TZ}
      - TELEGRAM_THREAD=1
      - CHECK_UPDATES=1
      - CHECK_UPDATE_EVERY_HOURS=24
      - BUTTON_COLUMNS=2
      - LANGUAGE=ES
      - EXTENDED_MESSAGES=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # NO CAMBIAR
      - /ruta/para/guardar/las/programaciones:/app/schedule # CAMBIAR LA PARTE IZQUIERDA
    image: dgongut/docker-controller-bot:latest
    container_name: DOCKER-BOT
    restart: always
    network_mode: host
    tty: true
#---------------------------------------------------------------#
# Servicio Monitoreo
  netdata:
    image: netdata/netdata
    container_name: NETDATA
    hostname: "NetData"
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=${TZ}  
    volumes:
      - '/etc/os-release:/host/etc/os-release:ro'
      - '/sys:/host/sys:ro'
      - '/proc:/host/proc:ro'
      - '/etc/group:/host/etc/group:ro'
      - '/etc/passwd:/host/etc/passwd:ro'
    ports:
      - '19999:19999/tcp'
    restart: always  
